app/users/models.py
from app import db
#from app.users import constants as USER
from flask.ext.mongoengine.wtf import model_form

# class User(db.Model):

#     __tablename__ = 'users_user'
#     id = db.Column(db.Integer, primary_key=True)
#     name = db.Column(db.String(50), unique=True)
#     email = db.Column(db.String(120), unique=True)
#     password = db.Column(db.String(120))
#     role = db.Column(db.SmallInteger, default=USER.USER)
#     status = db.Column(db.SmallInteger, default=USER.NEW)
#     #homepage = db.Column(

#     def __init__(self, name=None, email=None, password=None):
#       self.name = name
#       self.email = email
#       self.password = password

#     def getStatus(self):
#       return USER.STATUS[self.status]

#     def getRole(self):
#       return USER.ROLE[self.role]

#     def __repr__(self):
#         return '<User %r>' % (self.name)

class Content(db.EmbeddedDocument):
    title = db.StringField(max_length=120, required=True)
    url = db.StringField()
    children = db.ListField(db.StringField(max_length=30))

class Metadata(db.Document):
    last_modified = db.DateTimeField(help_text='date when last modified')
    date_uploaded = db.DateTimeField(help_text='date published')
    children_count = db.IntField(default=0)

class HomePage(db.EmbeddedDocument):
    name = db.StringField(max_length=50)    
    children = db.ListField(db.EmbeddedDocumentField(Content))
    content = db.EmbeddedDocumentField(Content)
    metadata = db.ReferenceField(Metadata)
    
class User(db.Document):
    username = db.StringField(max_length=50, required=True)
    email = db.StringField(required=True)
    password = db.StringField(required=True) 
    homepage = db.EmbeddedDocumentField(HomePage)
    role = db.StringField(max_length=20)
    status = db.StringField(max_length=10)
    session = db.DictField() #db.StringField() 
    tags = db.ListField(db.StringField(max_length=30))

    #_id
    
# UserForm = model_form(User)

# def add_user(request):
#     form = UserForm(request.POST)
#     if request.method == 'POST' and form.validate():
#         # do something
#         redirect('done')
#     return render_response('add_user.html', form=form)

app/users/forms.py
from flask.ext.wtf import Form, RecaptchaField
from wtforms import TextField, PasswordField, BooleanField
from wtforms.validators import Required, EqualTo, Email

class LoginForm(Form):
  email = TextField('Email address', [Required(), Email()])
  password = PasswordField('Password', [Required()])

class RegisterForm(Form):
  name = TextField('NickName', [Required()])
  email = TextField('Email address', [Required(), Email()])
  password = PasswordField('Password', [Required()])
  confirm = PasswordField('Repeat Password', [
      Required(),
      EqualTo('password', message='Passwords must match')
      ])
  accept_tos = BooleanField('I accept the TOS', [Required()])
  recaptcha = RecaptchaField()

app/__init__.py
# Import flask and template operators
from flask import Flask, render_template
# Import MongoEngine
from flask.ext.mongoengine import MongoEngine
# # Import SQLAlchemy
# from flask.ext.sqlalchemy import SQLAlchemy
import sys
import os

# Define the WSGI application object
app = Flask(__name__)

####### User Login Hack BEGINS
# from flask.ext.login import LoginManager
# from flask.ext.openid import OpenID
# from config import BASE_DIR

# lm = LoginManager()
# lm.init_app(app)
# oid = OpenID(app, os.path.join(BASE_DIR, 'tmp'))
####### User Login Hack ENDS

# Configurations
app.config.from_object('config')

# Define the database object which is imported
# by modules and controllers
#db = SQLAlchemy(app)
# # Build the database:
# # This will create the database file using SQLAlchemy
# db.create_all()

app.config["MONGODB_SETTINGS"] = { 
    "DB": os.environ.get("FLASK_DB"),
    "USERNAME": os.environ.get("FLASK_USER"),
    "PASSWORD": os.environ.get("FLASK_PASS"),
    "HOST": "127.0.0.1",
    "PORT": 27017 }
db = MongoEngine(app)

def install_secret_key(app, filename='secret_key'):
    """Configure the SECRET_KEY from a file
    in the instance directory.

    If the file does not exist, print instructions
    to create it from a shell with a random key,
    then exit.
    """
    filename = os.path.join(app.instance_path, filename)

    try:
        app.config['SECRET_KEY'] = open(filename, 'rb').read()
    except IOError:
        print('Error: No secret key. Create it with:')
        full_path = os.path.dirname(filename)
        if not os.path.isdir(full_path):
            print('mkdir -p {filename}'.format(filename=full_path))
        print('head -c 24 /dev/urandom > {filename}'.format(filename=full_path))
        sys.exit(1)

if not app.config['DEBUG']:
    install_secret_key(app)

# Sample HTTP error handling
@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

from app.users.views import mod as usersModule
app.register_blueprint(usersModule)

app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from werkzeug import check_password_hash, generate_password_hash

from app import db
from app.users.forms import RegisterForm, LoginForm
from app.users.models import User
from app.users.decorators import requires_login, logout_user

mod = Blueprint('users', __name__, url_prefix='/users')

@mod.route('/me/')
@requires_login
def home():
  #return render_template("users/profile.html", user=g.user)
  return redirect('/')

@mod.before_request
def before_request():
  """
  pull user's profile from the database before every request are treated
  """
  g.user = None
  if 'user_id' in session:
    #g.user = User.query.get(session['user_id'])
    print "session user_id: %s" % (session['user_id'])

@mod.route('/login/', methods=['GET', 'POST'])
def login():
  """
  Login form
  """
  form = LoginForm(request.form)
  # make sure data are valid, but doesn't validate password is right
  if form.validate_on_submit():
    #user = User.query.filter_by(email=form.email.data).first()
    try:
      user = User.objects.get(email=form.email.data)    
      # we use werzeug to validate user's password
      if check_password_hash(user.password, form.password.data): #optional: bool(user)
        # the session can't be modified as it's signed, 
        # it's a safe place to store the user id
        session['user_id'] = str(user.id)
        #flash('Success! Welcome %s!' % user.name)
        return redirect(url_for('home'))
    except:
      flash('Wrong email or password', 'error-message')
  return render_template("users/login.html", form=form)

@mod.route('/logout/')
def logout():
  """
  Remove user from session.
  """
  logout_user()
  return redirect('/')

@mod.route('/register/', methods=['GET', 'POST'])
def register():
  """
  Registration Form
  """
  form = RegisterForm(request.form)
  if form.validate_on_submit():
    # create an user instance not yet stored in the database
    user = User(username=form.name.data, email=form.email.data, \
      password=generate_password_hash(form.password.data))
    # Insert the record in our database and commit it
    user.save()
    #db.session.add(user)
    #db.session.commit()

    # Log the user in, as he now has an id
    session['user_id'] = str(user.id)
    print "session user_id: %s" % (str(user.id))
    # flash will display a message to the user
    #flash('Thanks for registering')
    # redirect user to the 'home' method of the user module.
    return redirect(url_for('users.home'))
  return render_template("users/register.html", form=form)

app/templates/base.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <title>{% block title %}My Site{% endblock %}</title>    
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='pygment_trac.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <!--[if lt IE 9]>
	<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
    {% block css %}
    <!--link rel="stylesheet" href="/static/css/reset-min.css" />
    <link rel="stylesheet" href="/static/css/main.css" /-->
    {% endblock %}
    {% block script %}
    <script src="/static/js/main.js" type="text/javascript"></script>
    {% endblock %}
  </head>

  <body>
    <div id="header">{% block header %}{% endblock %}</div>
    <div class="wrapper">
      <!--div id="messages-wrap"-->
      <div id="messages">
        {% for category, msg in get_flashed_messages(with_categories=true) %}
        <p class="message flash-{{ category }}">{{ msg }}</p>
        {% endfor %}
      </div>
    </div>
    <div id="content">{% block content %}{% endblock %}</div>
    <div id="footer">{% block footer %}{% endblock %}</div>
  </body>
</html>

app/templates/forms/macros.html
{% macro render_field(field) %}
<div class="form_field">
  {{ field.label(class="label") }}
  {% if field.errors %}
  {% set css_class = 'has_error ' + kwargs.pop('class', '') %}
  {{ field(class=css_class, **kwargs) }}
  <ul class="errors">{% for error in field.errors %}<li>{{ error|e }}</li>{% endfor %}</ul>
  {% else %}
  {{ field(**kwargs) }}
  {% endif %}
</div>
{% endmacro %}

app/templates/index.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <title>HomePage-Gen</title>
    
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='pygment_trac.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  </head>
  <body>

    <div class="wrapper">
      <p style="color: Green;">Minimalistic Homepage Generator</p>
    </div>
    <hr />

    <div class="col-lg-8"> 
      <ul>
	<li><a href="/new"><u>Add new</u></a></li>
	{% if users %}
	{% for user in users %}
	<!-- 
	<li><a href="/arcolife"><u>Arcolife's stuff</u></a></li>
	<li><a href="/cj"><u>CJ's stuff</u></a></li>
	-->
	<li><a href="/{{user.username}}"><u>{{user.username}}'s stuff</u></a></li>
	{% endfor %}
	{% endif %}
      </ul>
    </div>

    <div class="col-lg-3">
      <ul>
	{% if username %}
	<li><a href="/{{username}}">My stuff</a></li>
	<li><a href="/users/logout/">Logout</a></li>
	{% else %}
	Not logged In!
	<br />
	<li><a href="/users/login/">Login here</a></li>
	<li><a href="/users/register/">Register here</a></li>
	{% endif %}
      </ul>
    </div>
    
  </body>
  <script src="{{ url_for('static', filename='scale.fix.js') }}"></script>
</html>

app/templates/profile.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <title>My profile</title>
    
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='pygment_trac.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <!--[if lt IE 9]>
	<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
  </head>
  <body>
    <div class="wrapper">
      <p>User id is : {{ id }}</p>
    </div>
  </body>
</html>

app/templates/profiles/arcolife.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    
    <title>Arcolife&#39;s minimalist homepage</title>
    <link rel="shortcut icon" href="https://ssl.gstatic.com/docs/documents/images/kix-favicon6.ico">
    <style type="text/css">
      body {
      font-family: arial, sans, sans-serif;
      margin: 0;
      }

      iframe {
      border: 0;
      frameborder: 0;
      height: 100%;
      width: 100%;
      }

      #header, #footer {
      background: #f0f0f0;
      padding: 10px 10px;
      }

      #header {
      border-bottom: 1px #ccc solid;
      }

      #footer {
      border-top: 1px #ccc solid;
      border-bottom: 1px #ccc solid;
      font-size: 13;
      }

      #contents {
      margin: 6px;
      }

      .dash {
      padding: 0 6px;
      }
    </style>
    
    <link rel="stylesheet" href="{{ url_for('static', filename='mhp.css') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='mhp.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='mhp1.js') }}"></script>
  </head>
  <body>
    
    <div id="header">Arcolife&#39;s minimalist homepage</div>
    <div id="contents">
      <p class="c7"><span class="c0">Writing / Ideas</span></p>      
      <ul class="c6 lst-kix_i5gqit5vn3ci-2 start">
	<li class="c4"><span class="c0">Twitter:</span>
	  <span class="c3">
	    <a class="c5" href="twitter.com/arcolife">@arcolife</a>
	  </span>
	</li>
	<li class="c4"><span class="c0">Blog:</span>
	  <span class="c3">
	    <a class="c5" href="http://blog.arcolife.in">TecHunger</a>
	  </span>
	</li>
	<li class="c4"><span class="c0">Nerd stuff:</span>
	  <span class="c3">
	    <a class="c5" href="http://coderiddles.blogspot.in">The Quintessential Snippets</a>
	  </span>
	</li>
      </ul>

      <br />
      <p class="c7">
	<span class="c0">Projects</span>
      </p>
      <ul class="c6 lst-kix_khbmqhsxwaob-2 start">
	<li class="c4">
	  <span class="c3"><a class="c5" href="http://work.arcolife.in">Portfolio</a></span>
	</li>
      </ul>
      
      <br />
      <p class="c7"><span class="c0">Music</span>
      <ul class="c6 lst-kix_wun2mhhhc9rp-2 start">
	<li class="c4">
	  <span class="c3"><a class="c5" href="http://soundcloud.com/arcolife">soundcloud.com/arcolife</a></span>
	</li>
      </ul>
      </p>

      <br />
      <p class="c7">
	<span class="c0">Repos</span>
      <ul class="c6 lst-kix_t99m7rwxnsrs-2 start">
	<li class="c4">
	  <span class="c3">
	    <a class="c5" href="https://github.com/arcolife">github.com/arcolife</a>
	  </span>
	</li>
      </ul>
      </p>

      <br />
      <p class="c7">
	<span class="c3">
	  <a class="c5" href="mailto:arcshams@gmail.com">Email</a>
	</span>
      </p>
    </div>
  </body>
  <script type="text/javascript" src="{{ url_for('static', filename='mhp2.js') }}"></script>
</html>

app/templates/profiles/jacobcole.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    
    <title>Jacob&#39;s minimalist homepage</title>
    <link rel="shortcut icon" href="https://ssl.gstatic.com/docs/documents/images/kix-favicon6.ico">
    <style type="text/css">
      body {
      font-family: arial, sans, sans-serif;
      margin: 0;
      }

      iframe {
      border: 0;
      frameborder: 0;
      height: 100%;
      width: 100%;
      }

      #header, #footer {
      background: #f0f0f0;
      padding: 10px 10px;
      }

      #header {
      border-bottom: 1px #ccc solid;
      }

      #footer {
      border-top: 1px #ccc solid;
      border-bottom: 1px #ccc solid;
      font-size: 13;
      }

      #contents {
      margin: 6px;
      }

      .dash {
      padding: 0 6px;
      }
    </style>
    
    <link rel="stylesheet" href="{{ url_for('static', filename='mhp.css') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='mhp.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='mhp1.js') }}"></script>
  </head>
  <body>

    <div id="header">Jacob&#39;s Stuff (Min.)</div><div id="contents">

      (under construction)
      <hr>
    </div>
  </body>
  <script type="text/javascript" src="{{ url_for('static', filename='mhp2.js') }}"></script>
</html>

app/templates/test2.html
{% block body_content %}
<div class="container">
  <div class="page-header">
    <h1>Hello, {{name}}!</h1>
  </div>
</div>
{% endblock %}

app/templates/users/login.html
{% extends "base.html" %}
{% block content %}
{% from "forms/macros.html" import render_field %}
<form method="POST" action="." class="form">
  {{ form.csrf_token }}
  {{ render_field(form.email, class="input text") }}
  {{ render_field(form.password, class="input text") }}
  <input type="submit" value="Login" class="button green">
</form>
<a href="{{ url_for('users.register') }}">Register</a>
{% endblock %}

app/templates/users/profile.html
{% extends "base.html" %}
{% block content %}
Hi {{ user.name }}!
{% endblock %}

app/templates/users/register.html
{% extends "base.html" %}
{% block content %}
{% from "forms/macros.html" import render_field %}
<form method="POST" action="." class="form">
  {{ form.csrf_token }}
  {{ render_field(form.name, class="input text") }}
  {{ render_field(form.email, class="input text") }}
  {{ render_field(form.password, class="input text") }}
  {{ render_field(form.confirm, class="input text") }}
  {{ render_field(form.accept_tos, class="input checkbox") }}
  <label>ReCaptcha</label>
  {{ form.recaptcha }}
  <input type="submit" value="Register" class="button green">
</form>
<a href="{{ url_for('users.login') }}">Login</a>
{% endblock %}